apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kogeneesti.fullname" . }}-config
  labels:
    {{- include "kogeneesti.labels" . | nindent 4 }}
data:
  KOGENEESTI_CORS_ALLOWED_ORIGINS: {{ .Values.env.corsAllowedOrigins | quote }}
  KOGENEESTI_CORS_ALLOWED_METHODS: {{ .Values.env.corsAllowedMethods | quote }}
  KOGENEESTI_CORS_ALLOWED_HEADERS: {{ .Values.env.corsAllowedHeaders | quote }}
  KOGENEESTI_STORAGE_LOCATION: {{ ternary .Values.persistence.mountPath .Values.env.storageLocation .Values.persistence.enabled | quote }}
