{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kogeneesti.secretName" . }}
  labels:
    {{- include "kogeneesti.labels" . | nindent 4 }}
type: Opaque
stringData:
  KOGENEESTI_JDBC_URL: {{ .Values.env.jdbcUrl | quote }}
  KOGENEESTI_DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
{{- end }}
